# Generated by Django 5.1.15 on 2026-08-14 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='employee_number',
            field=models.CharField(blank=True, default='', help_text='Internal employee number or badge ID.', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='shift',
            field=models.CharField(choices=[('1st', '1st Shift'), ('2nd', '2nd Shift')], default='1st', help_text='The shift the employee normally works.', max_length=10),
        ),
        migrations.AddField(
            model_name='userqualification',
            name='last_recertified_at',
            field=models.DateTimeField(blank=True, help_text='The date the certification was last re-verified.', null=True),
        ),
        migrations.AddField(
            model_name='userqualification',
            name='quarterly_recertification_due',
            field=models.DateTimeField(blank=True, help_text='Next scheduled quarterly recertification review date.', null=True),
        ),
    ]
