# Generated by Django 5.1.15 on 2026-08-14 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='shift',
            field=models.CharField(blank=True, choices=[('first', 'First Shift'), ('second', 'Second Shift')], max_length=10),
        ),
    ]
