# Generated by Django 5.1.15 on 2026-08-14 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_user_shift'),
        ('access', '0003_employeetraining'),
    ]

    operations = [
    ]
