# Generated by Django 5.1.15 on 2026-08-14 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0004_merge_0002_user_shift_0003_employeetraining'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='shift',
            field=models.CharField(blank=True, choices=[('1st', 'First Shift'), ('2nd', 'Second Shift')], default='', help_text='The shift the employee works. Blank for staff not on a floor shift.', max_length=10),
        ),
    ]
